###################################################################

# Created by write_sdc on Fri May  2 12:16:11 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_wire_load_model -name 16000 -library saed32lvt_tt0p85v25c
set_max_transition 0.2 [current_design]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports A2D_MISO]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports hallGrn]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports hallYlw]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports hallBlu]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports inertMISO]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports inertINT]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports cadence]
set_driving_cell -lib_cell NAND2X2_LVT [get_ports tgglMd]
set_load -pin_load 50 [get_ports A2D_SS_n]
set_load -pin_load 50 [get_ports A2D_MOSI]
set_load -pin_load 50 [get_ports A2D_SCLK]
set_load -pin_load 50 [get_ports highGrn]
set_load -pin_load 50 [get_ports lowGrn]
set_load -pin_load 50 [get_ports highYlw]
set_load -pin_load 50 [get_ports lowYlw]
set_load -pin_load 50 [get_ports highBlu]
set_load -pin_load 50 [get_ports lowBlu]
set_load -pin_load 50 [get_ports inertSS_n]
set_load -pin_load 50 [get_ports inertSCLK]
set_load -pin_load 50 [get_ports inertMOSI]
set_load -pin_load 50 [get_ports TX]
set_load -pin_load 50 [get_ports {LED[1]}]
set_load -pin_load 50 [get_ports {LED[0]}]
create_clock [get_ports clk]  -period 2.5  -waveform {0 1.25}
set_clock_uncertainty 0.15  [get_clocks clk]
set_input_delay -clock clk  0.3  [get_ports RST_n]
set_input_delay -clock clk  0.3  [get_ports A2D_MISO]
set_input_delay -clock clk  0.3  [get_ports hallGrn]
set_input_delay -clock clk  0.3  [get_ports hallYlw]
set_input_delay -clock clk  0.3  [get_ports hallBlu]
set_input_delay -clock clk  0.3  [get_ports inertMISO]
set_input_delay -clock clk  0.3  [get_ports inertINT]
set_input_delay -clock clk  0.3  [get_ports cadence]
set_input_delay -clock clk  0.3  [get_ports tgglMd]
set_output_delay -clock clk  0.5  [get_ports A2D_SS_n]
set_output_delay -clock clk  0.5  [get_ports A2D_MOSI]
set_output_delay -clock clk  0.5  [get_ports A2D_SCLK]
set_output_delay -clock clk  0.5  [get_ports highGrn]
set_output_delay -clock clk  0.5  [get_ports lowGrn]
set_output_delay -clock clk  0.5  [get_ports highYlw]
set_output_delay -clock clk  0.5  [get_ports lowYlw]
set_output_delay -clock clk  0.5  [get_ports highBlu]
set_output_delay -clock clk  0.5  [get_ports lowBlu]
set_output_delay -clock clk  0.5  [get_ports inertSS_n]
set_output_delay -clock clk  0.5  [get_ports inertSCLK]
set_output_delay -clock clk  0.5  [get_ports inertMOSI]
set_output_delay -clock clk  0.5  [get_ports TX]
set_output_delay -clock clk  0.5  [get_ports {LED[1]}]
set_output_delay -clock clk  0.5  [get_ports {LED[0]}]
